import {InMemoryDbService} from 'angular-in-memory-web-api';

// tslint:disable:max-line-length
export class InMemoryDataService implements InMemoryDbService {
  createDb() {
    const heroes = [
      {id: 1, name: 'Vision', heroType: 'hero', imageName: 'Vision.jpg', bio: 'The metal monstrosity called Ultron, constructed by the size-changing scientist Henry Pym himself, inadvertently gained sentience and rebelled against the Avengers\'s resident roboticist. After six months of failure, Ultron kidnapped the first Human Torch\'s initial creator, Professor Phineas T. Horton. Ultron decided to create his own android using the android Human Torch of the 1940s (actually a divergent Human Torch created by Immortus for his own machinations) to serve as a vehicle of vengeance against the Avengers. Ultron had Professor Horton color the android\'s face red, and also had Professor Horton alter the Horton Cells of which the Torch consisted, giving his creation density-shifting powers. When the Vision was "birthed," however, Ultron discovered that Professor Horton had not erased or destroyed the Vision\'s memories as the Torch. Ultron killed Professor Horton for having betrayed him, and the "Torch" sought vengeance. Ultron defeated him and endowed the Vision\'s neural processors with the brain patterns of Simon Williams, the ionically charged costumed champion called Wonder Man, implanting a control crystal to keep him in check.'},
      {id: 2, name: 'Scarlet Witch', heroType: 'hero', imageName: 'Scarlet_Witch.jpg', bio: 'Wanda Lensherr, the Scarlet Witch, was the daughter of Magneto and the sister of Quicksilver. She had the ability to alter probability fields with her hex-spheres. Wanda was a passive member of Magneto\'s team, and after her father\'s apparent death, began working with the Brotherhood, participating in the rescue of the X-Men from Weapon X. She helped lead the Brotherhood for a while, all the while keeping in touch with Charles Xavier to promote a more peaceful mutant-human integration. When Magneto returned, she and her brother fled, although he caught them. Magneto injured Quicksilver, but left Wanda unhurt. Eventually, both Wanda and her brother joined the Ultimates.'},
      {id: 3, name: 'Captain America', heroType: 'hero', imageName: 'Captain_America.jpg', bio: 'Steve Rogers was born July 4, 1920, to poor Irish immigrant parents, Sarah and Joseph Rogers. Rogers grew up a frail youth during the Great Depression in America. Little else is known about Rogers\' early life other than the fact that a strong sense of duty, honor, and humility was instilled in him; perhaps due to his Irish Catholic upbringing. Rogers\' father died when he was a child and his mother died from pneumonia later, when he was in his late teens.'},
      {id: 4, name: 'Hulk', heroType: 'hero', imageName: 'Hulk.jpg', bio: 'Robert Bruce Banner is the son of Dr. Brian Banner, an atomic physicist, and his wife Rebecca. Although Rebecca deeply loved Bruce, who returned her affection, Brian hated their child. Brian never wanted children because of what happened to him and his sisters Susan and Elaine Banner. An alcoholic, and a very, very angry man, Brian was driven by an insane jealousy of Bruce for being an object of Rebecca\'s love. Further, Brian believed that his radiation work had altered his DNA and given him a mutant son. These factors led to Brian abusing Bruce physically. One of the people who helped Bruce cope with Brian\'s tantrums was his maternal cousin Jennifer Walters, with whom Bruce used to spend summers in the public library reading for hours, losing themselves to books. '},
      {id: 5, name: 'Iron Man', heroType: 'hero', imageName: 'Iron_Man.jpg', bio: 'The biological parents of Tony Stark were two S.H.I.E.L.D. agents, Amanda Armstrong and Jude, who met during a courier mission. After Jude saved Amanda from an assassin, they got to know each other and fell in love. Following a two-year relationship, Amanda became pregnant. A week before giving birth to the baby, Jude revealed to have been a Hydra double-agent with little regard for anybody but Amanda and himself who sold out fellow S.H.I.E.L.D. soldiers, and was even responsible for the incident that had almost cost Amanda her life. During a discussion when he was trying to convince Amanda to accept Hydra\'s protection, she attacked Jude and killed him.'},
      {id: 6, name: 'Captain Marvel', heroType: 'hero', imageName: 'Captain_Marvel.jpg', bio: 'Carol Danvers grew up as the oldest child of three in a traditional Boston home, with a contractor father who believed in the merits of hard work. When he built their Cape Cod summer home, Carol insisted on working as hard as her two younger brothers, trying to make equal in her father\'s eyes. A voracious reader, she dreamed of becoming an astronaut and traveling to distant planets; as a teen she even hitchhiked to Cape Canaveral to view a launch there. Her father however, could not accept women as men\'s equals, and when financial troubles meant he could only send one child to college, he chose middle child Steve despite Carol\'s superior grades.'},
      {id: 7, name: 'Black Widow', heroType: 'hero', imageName: 'Black_Widow.jpg', bio: 'When the United States and Russian governments sent Natasha Romanova after the Deathless Frenzy, Yuri Stalyenko sent Yelena from the Red Room, at her own insistence, to shadow Natasha to ensure that the serum ended up in Russian hands. After being fooled into thinking Natasha was dead, Yelena headed to Rhapastan to stop General Khan and the Deathless Frenzy. She failed and was captured. It was only through the efforts of Natasha Romanova that Khan\'s plans failed, although Yelena learned some important lessons from her failing.'},
      {id: 8, name: 'Thor', heroType: 'hero', imageName: 'Thor.jpg', bio: 'Thor is the blood-son of Odin, All-Father of the Asgardians, and Jord, who was also known as Gaea, the goddess who was one of the Elder Gods. Odin sought to father a son whose power would derive from both Asgard and Midgard (as the Earth realm is called by Asgardians), and hence he sought to mate with Jord. Odin created a cave in Norway where Jord gave birth to Thor. Months after the infant Thor was weaned, Odin brought him to Asgard to be raised. Odin\'s wife, the goddess Frigga, acted as Thor\'s mother from that time onward. Not until many decades later did Thor learn that Jord was his birth mother.'},
      {id: 9, name: 'Quicksilver', heroType: 'hero', imageName: 'Quicksilver.jpg', bio: 'Pietro Maximoff was kidnapped from Serbia and brought to Wundagore Mountain, base of the High Evolutionary, he and his twin sister, Wanda, were the children of Romany couple, Django and Marya Maximoff. The High Evolutionary supposedly abducted the twins when they were babies and experimented on them, once he was disgusted with the results, he returned them to Wundagore, disguised as regular mutants.'},
      {id: 10, name: 'Hawkaye', heroType: 'hero', imageName: 'Hawkaye.jpg', bio: 'Clinton "Clint" Barton was born to Harold and Edith Barton. He grew up working in his father\'s Butchers shop in Waverly, Iowa with his older brother, Barney. Their father was abusive, especially when he drank and continually beat the young boys; Barney taught Clint how to fight and helped him to improve his aim. Harold\'s drinking eventually cost him his life along with his wife when both died in a car accident. Clint and Barney were sent to numerous foster homes; while running away from one of them, they encountered and joined a traveling circus where the pair worked as roustabouts. While a member of the circus, Clint was trained by the original Swordsman and by Trick Shot. Clint later found the Swordsman embezzling money from the carnival. Before he could turn his mentor over to the authorities, Clint was beaten and left for dead, allowing the Swordsman to escape town. Clint\'s relationship with his brother Barney and Trick Shot soon deteriorated as well.'},
    ];
    return {heroes};
  }
}
